export enum TipoUsuario {
    DUEÑO = 'DUEÑO',
    SUPERVISOR = 'SUPERVISOR',
    MOZO = 'MOZO',
    COCINERO = 'COCINERO',
    BARTENDER = 'BARTENDER',
    CLIENTE_REGISTRADO = 'CLIENTE_REGISTRADO',
    CLIENTE_ANONIMO = 'CLIENTE_ANONIMO'
}
